# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale                   : "en-GB"
title                    : "Dr. Matthew Bradbury"
title_separator          : "-"
name                     : &name "Dr. Matthew Bradbury"
description              : &description "Lecturer at Lancaster University"
url                      : https://MBradbury.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "MBradbury/MBradbury.github.io"
initial_year             : 2021
teaser                   :  # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
breadcrumbs              : false # true, false (default)
future                   : true
read_more                : "disabled" # if enabled, adds "Read more" links to excerpts
date_format              : "%d %B %Y"
atom_feed:
  path                   : # blank (default) uses feed.xml
  hide                   : true

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : &twitter "MattBradbury_"
linkedin:
  username               : "matthewstephenbradbury"
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :  # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : "Person" # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
   - "https://twitter.com/MattBradbury_"
   - "https://www.linkedin.com/in/matthewstephenbradbury"
   - "https://www.research.lancs.ac.uk/portal/en/people/matthew-bradbury(a725915d-0988-4573-8d81-5784ead7fd75).html"


# Site Author
author:
  name             : "Dr. Matthew Bradbury"
  avatar           : "/images/profile.png"
  bio              : "Matthew Bradbury is a Lecturer conducting research into security, context privacy and trust assessment in resource-constrained and distributed systems."
  location         : 
  employer         : "Lancaster University"
  employer_url     : "https://www.lancaster.ac.uk/scc/research/security/"
  email            : m.s.bradbury@lancaster.ac.uk
  uri              : "https://www.research.lancs.ac.uk/portal/en/people/matthew-bradbury(a725915d-0988-4573-8d81-5784ead7fd75).html"
  links: &author_links
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/MattBradbury_"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/matthewstephenbradbury"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/MBradbury"
    #- label: "GitLab"
    #  icon: "fab fa-fw fa-gitlab"
    #  url:
    #- label: "Bitbucket"
    #  icon: "fab fa-fw fa-bitbucket"
    #  url:
    - label: "DBLP"
      icon: "ai ai-fw ai-dblp-square"
      url: "https://dblp.uni-trier.de/pers/hd/b/Bradbury:Matthew"
    - label: "Google Scholar"
      icon: "ai ai-fw ai-google-scholar"
      url: "https://scholar.google.co.uk/citations?user=U1KPCasAAAAJ"
    - label: "Semantic Scholar"
      icon: "ai ai-fw ai-semantic-scholar"
      url: "https://www.semanticscholar.org/author/M.-Bradbury/31941534"
    - label: "ORCID"
      icon: "ai ai-fw ai-orcid-square"
      url: "https://orcid.org/0000-0003-4661-000X"
    #- label: "ResearchGate"
    #  icon: "fab fa-fw fa-researchgate"
    #  url: "https://www.researchgate.net/profile/Matthew_Bradbury2"
    #- label: "Microsoft Academic"
    #  icon: ""
    #  url: "https://academic.microsoft.com/author/2128542392"
    #- label: "WRAP"
    #  icon: "fab fa-fw fa-link"
    #  url: "https://wrap.warwick.ac.uk/view/author_id/39286.html"

footer:
  links: *author_links

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - CONTRIBUTING.md
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "<!-- readmore -->"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Collections
collections:
  publications:
    output: true
    sort_by: publishDate
    permalink: /:collection/:path/
  publications_hidden:
    output: false
  projects:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/


# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single-project
      author_profile: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single-publication
      author_profile: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true

# Sass/SCSS
# http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
sass:
  sass_dir: _sass
  style: compressed


# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Europe/London


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
