# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale                   : "en-GB"
title                    : "Dr. Matthew Bradbury"
title_separator          : "-"
name                     : &name "Dr. Matthew Bradbury"
description              : &description "Lecturer at Lancaster University"
url                      : https://MBradbury.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "MBradbury/MBradbury.github.io"
teaser                   :  # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
breadcrumbs              : false # true, false (default)
future                   : true
read_more                : "disabled" # if enabled, adds "Read more" links to excerpts
date_format              : "%d %B %Y"
atom_feed:
  path                   : # blank (default) uses feed.xml
  hide                   : true

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : &twitter "MattBradbury_"
linkedin:
  username               : "matthewstephenbradbury"
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :  # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
   - "https://twitter.com/MattBradbury_"
   - "https://www.linkedin.com/in/matthewstephenbradbury"


# Site Author
author:
  name             : "Dr. Matthew Bradbury"
  avatar           : "/images/profile.png"
  bio              : "Matthew Bradbury is a Lecturer conducting research into security, context privacy and trust assessment in resource-constrained and distributed systems."
  location         : 
  employer         : "Lancaster University"
  employer_url     : "https://www.lancaster.ac.uk/scc/research/security/"
  pubmed           :
  googlescholar    : "https://scholar.google.co.uk/citations?user=U1KPCasAAAAJ"
  email            : m.s.bradbury@lancaster.ac.uk
  researchgate     : "https://www.researchgate.net/profile/Matthew_Bradbury2"
  #uri              : "https://warwick.ac.uk/matthewbradbury"
  microsoftacademic: "https://academic.microsoft.com/author/2128542392"
  semanticscholar  : "https://www.semanticscholar.org/author/M.-Bradbury/31941534"
  bitbucket        : 
  codepen          :
  dblp             : "https://dblp.uni-trier.de/pers/hd/b/Bradbury:Matthew"
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "MBradbury"
  google_plus      :
  keybase          :
  instagram        :
  impactstory      : #"https://profiles.impactstory.org/u/xxxx-xxxx-xxxx-xxxx"
  lastfm           :
  linkedin         : "matthewstephenbradbury"
  orcid            : "https://orcid.org/0000-0003-4661-000X"
  pinterest        :
  soundcloud       :
  stackoverflow    : # https://stackoverflow.com/users/123456/username
  steam            :
  tumblr           :
  twitter          : "MattBradbury_"
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :
  #warwick_wrap     : "39286"


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - CONTRIBUTING.md
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "<!-- readmore -->"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Collections
collections:
  publications:
    output: true
    sort_by: publishDate
    permalink: /:collection/:path/
  publications_hidden:
    output: false
  projects:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/


# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single-project
      author_profile: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single-publication
      author_profile: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: Europe/London # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
