# Configuration file for the `fontite` icon font optimizer.

# Required section specifying what kind of fonts to output and where.
[outputs.fonts]
# Desired output font formats. Use any extension supported by FontForge.
formats = ['woff2', 'woff', 'ttf', 'svg', 'eot']
# The filename, without the extension, for each of the generated fonts.
filename = 'site-icons'
# Directory, either relative or absolute, in which to create all of the font
# files.
dir = '../assets/fonts/'

# CSS output is optional. If you only need font files, this section can be
# omitted.
[outputs.css]
# Path, either relative or absolute, to where the final CSS file should be
# generated.
path = './output/fontite.css'
# A URL, minus the filename, where fonts will be accessible relative to the CSS
# file on the webserver. This should always end with a `/` separator.
font_url = '/assets/fonts/'
# A class name that should be added to every icon.
icon_class = 'icon'
# A class name prefix used for each icon.
icon_class_prefix = 'si-'

[sources.base_settings_font]
path = './fonts/fa-solid-900.woff2'

# Specifies glyphs to copy from an existing font.
[sources.fonts.fa-brands]
path = './fonts/fa-brands-400.woff2'
icons = [
    'linkedin',
    'creative-commons-by',
    'twitter-square',
    'github',
]

# Specifies glyphs to copy from another existing font.
[sources.fonts.fa-solid]
path = './fonts/fa-solid-900.woff2'
icons = [
    'calendar',
    'map-marker',
    'map-marker-alt',
    'link',
    'envelope-square',
    'folder-open',
    'asterisk',
    'file',
    'file-pdf',
    'file-image',
    'file-powerpoint',
    'database',
    'project-diagram',
    'ellipsis-h',
    'tags',
    'volume-up',
    'users',
    'briefcase',
    'book',
    'check-square',
    'desktop',
]

#[sources.fonts.fa-regular]
#path = '../assets/fonts/fa-regular-900.woff2'
#icons = [
#    'css3-alt',
#]

[sources.fonts.academicicons]
path = './fonts/academicons.woff2'
icons = [
    'dblp-square',
    'google-scholar',
    'semantic-scholar',
    'orcid',
    'scopus',
]
